name: auto action runner
run-name: ${{ github.actor }} is running
on:
  schedule:
    - cron: '50 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: run
        run: pnpm dev ${{ secrets.ACCOUNT }} ${{ secrets.PASSWORD }}
